# =========================
# WRN LifePlugin Config
# =========================

# Standard Leben (für neue Spieler)
default-lives: 3

# Maximale Leben (für GUI Limit)
max-lives: 10

# =========================
# SERVER MODE SYSTEM
# =========================
mode:
  current: hardcore

# =========================
# MARKETPLACE MODES
# =========================
marketplace:

  hardcore:
    name: Hardcore
    lives: 1
    banOnZero: true

  pro:
    name: Pro
    lives: 5
    banOnZero: false

  vanilla_plus:
    name: Vanilla+
    lives: 3
    banOnZero: true

# =========================
# PLAYER DATA (AUTO)
# =========================
lives: {}

# =========================
# SETTINGS
# =========================
settings:
  actionbar: true
  update-interval: 40
