name: LifeCore
version: 2.0-Beta
main: de.felix.lifeplugin.Main
api-version: 1.21
author: WRNlabs

depend:
  - WRN-API

commands:
  livesgui:
    description: Öffnet das Lives GUI
    usage: /livesgui
    aliases:
      - lives
      - leben
      - life

  langgui:
    description: Öffnet das Language GUI
    usage: /langgui
    aliases:
      - lang
      - language
      - langs

  modegui:
    description: Öffnet das Mode GUI
    usage: /modegui
    aliases:
      - mode
      - modes

  market:
    description: Öffnet den Marketplace
    usage: /market

permissions:
  life.admin:
    description: Darf Leben ändern
    default: op