name: LifePlugin
version: 1.0
main: de.felix.lifeplugin.Main
api-version: 1.21

commands:
  livesgui:
    description: Open Lives GUI
  language:
    description: Change language
  mode:
    description: Change mode

permissions:
  lifeplugin.admin:
    description: Erlaubt Mode Änderungen
    default: op
